version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.9"
  apt_packages:
    - gcc-10
  commands:
    - pip install poetry
    - poetry install --with docs
    - poetry run make html --directory=docs SPHINXOPTS="-W --keep-going -n"
    - mkdir _readthedocs/
    - mv docs/build/html _readthedocs/ 
