version: 2

build:
  os: ubuntu-20.04
  tools:
    python: "3.9"
  commands:
    - pip install poetry
    - poetry install --with docs
    - (cd docs && poetry run make html)
    - mv docs/build/html _readthedocs/ 
