version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  jobs:
    post_create_environment:
      - pip install poetry==1.7.1
      - poetry config virtualenvs.create false
    post_install:
      - poetry install --with docs,examples
      - pip list
      - poetry show

sphinx:
  configuration: docs/source/conf.py
