[tool.poetry]
name = "pyvrp"
version = "1.0.0"
description = "A state-of-the-art vehicle routing problem solver."
authors = [
    "Niels Wouda <nielswouda@gmail.com>",
    "Leon Lan <leon.lanyidong@gmail.com>",
    "Wouter Kool <wouter.kool@ortec.com>",
]
license = "MIT"
readme = "README.md"
repository = "https://github.com/N-Wouda/pyvrp"
include = [
    "LICENSE.md",
]
exclude = [
    "pyvrp/cpp/**/*",  # TODO do include in source dist?
]
packages = [
    { include = "pyvrp" },
]
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "Development Status :: 5 - Production/Stable",
    "Topic :: Software Development",
    "Topic :: Scientific/Engineering",
]

[tool.poetry.urls]
"Tracker" = "https://github.com/N-Wouda/pyvrp/issues"

[tool.poetry.dependencies]
python = "^3.7"
numpy = ">=1.15.2"
cvrplib = "^0.1.1"

[tool.poetry.dev-dependencies]
pre-commit = "^2.20.0"
pytest = ">=6.0.0"
pytest-cov = ">=2.6.1"
codecov = "*"

[tool.black]
line-length = 79

[tool.isort]
case_sensitive = true
line_length = 79
profile = "black"

[tool.mypy]
ignore_missing_imports = true

[tool.pytest.ini_options]
addopts = "--cov=. --cov-report=xml"
testpaths = "pyvrp"

[tool.coverage.run]
omit = [
    "*/tests/*",
    "venv/*",
    "docs/*",
]

[tool.coverage.report]
exclude_lines = [
    # This excludes all abstract methods from code coverage checks,
    # as they are never instantiated directly anyway
    "pragma: no cover",
    "@abstract",
]

[tool.poetry.build]
script = "build.py"

[build-system]
requires = ["poetry-core>=1.0.0", "scikit-build", "cmake"]
build-backend = "poetry.core.masonry.api"
