[genetic]
repair_probability = 0.50
collect_statistics = false
intensify_probability = 0.15
intensify_on_best = false
nb_iter_no_improvement = 20_000


[population]
min_pop_size = 25
generation_size = 40
nb_elite = 4
nb_close = 5
lb_diversity = 0.1
ub_diversity = 0.5


[penalty]
init_capacity_penalty = 20
init_time_warp_penalty = 6
repair_booster = 12
num_registrations_between_penalty_updates = 50
penalty_increase = 1.34
penalty_decrease = 0.32
target_feasible = 0.20
