name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        include:
          - compiler: gcc
            version: 9  # minimum gcc version
          - compiler: gcc
            version: latest
          - compiler: clang
            version: 11  # minimum clang version
          - compiler: clang
            version: latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - if: matrix.compiler == 'clang'
        name: Set up clang
        uses: egor-tensin/setup-clang@v1
        with:
          version: ${{ matrix.version }}
      - if: matrix.compiler == 'gcc'
        name: Set up GCC
        uses: egor-tensin/setup-gcc@v1
        with:
          version: ${{ matrix.version }}
      - uses: DoozyX/clang-format-lint-action@v0.13
        with:
          source: hgs/src hgs/include hgs/test
          extensions: h, cpp
          clangFormatVersion: 11
      - name: Make all
        run: |
          cmake -Brelease -Shgs
          make --directory=release
      - name: Test all
        run: |
          cd release
          ctest
      - uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          gcov: true
          # TODO gcov include/ignore
