name: CI

on:
  push:
    branches: [ main]
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        os: [ 'ubuntu-latest' ]
        compiler: [ 'gcc', 'clang' ]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - if: matrix.compiler == 'clang'
        name: Set up clang
        uses: egor-tensin/setup-clang@v1
      - if: matrix.compiler == 'gcc'
        name: Set up GCC
        uses: egor-tensin/setup-gcc@v1
        with:
          version: 9
      - uses: DoozyX/clang-format-lint-action@v0.13
        with:
          source: hgs/src hgs/include
          extensions: h, cpp
          clangFormatVersion: 11
      - name: Make all
        run: |
          cmake -Brelease -Shgs
          make --directory=release
      - name: Test all
        run: |
          cd release
          ctest
      - uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          gcov: true
          gcov_exclude: hgs/test/*.cpp
